### ISSUE TITLE
Filter the library by document type

### ISSUE THREAD

**Issue by ccoffey1** [dsarlo/word-by-word#14]
Code reviewer: @dsarlo 
User should be able to sort the documents in their library by file extension.

**Comment by dsarlo** [comment]
@ccoffey1 I don't like the placement of the filter, perhaps the top left would be better? Also, that funnel icon is a bit ugly. Maybe just having a label to the left side of it saying "Filter: " or something would be better? Or maybe just leave it where it is and remove the filter icon. It's too big and ugly lol.

Other than the UI, it works great! Worked perfectly with pdf's, png's and jpg's all in the same view!

![image](https://user-images.githubusercontent.com/16106087/52928286-ec624c80-330c-11e9-9b42-63b14b8cc1a8.png)

![image](https://user-images.githubusercontent.com/16106087/52928356-54b12e00-330d-11e9-9d56-c32909fe20a7.png)

**Comment by dsarlo** [comment]
@ccoffey1 Looking into the performance for this: AddFilterExtensions(_library.Select(file => file.FilePath));

Might be a better place to put it.

**Comment by ccoffey1** [comment]
@dsarlo I agree with the filter icon removal. I personally like it in the bottom right but if the general consensus is the upper left I'll shoot it there, no biggie. 

As for AddFilterExtensions(_library.Select(file => file.FilePath)); I need to initially iterate over all the documents loaded into the library (via LoadLibrary()), so I just put it in the property, since we only ever assign to library when we load the user's saved documents (after we de-serialize the observable collection). The other spot I could put it is directly in LoadLibrary().

**Comment by dsarlo** [comment]
@ccoffey1 Yeah @dcgoings agrees that it should be in the top left if you don't mind moving it. I meant to link a different part of your commit, not that line specifically, but it's no biggie. I just checked it out and everything is great! Good stuff!

**Comment by ccoffey1** [comment]
Oh okay dopeski. Moving the element to the left now!

**Comment by ccoffey1** [comment]
Moved to the left and closing the issue!
