### ISSUE TITLE
Sentences don't split properly on certain punctuation + quotes

### ISSUE THREAD

**Issue by ccoffey1** [dsarlo/word-by-word#22]
Sentences ending with punctuation and quotes don't split, such as:

"The quick brown fox jumped over the lazy dog!" She exclaimed. 

Would be considered one whole sentence, rather than two.

**Comment by dcgoings** [comment]
https://stackoverflow.com/questions/25735644/python-regex-for-splitting-text-into-sentences-sentence-tokenizing

**Comment by dsarlo** [comment]
@ccoffey1 Can we get this added and tested soon? This was supposed to be done last sprint. Not sure if you remembered you set the sprint 1 tag that's all.

**Comment by ccoffey1** [comment]
@dsarlo Yeah I didn't see it was tagged for sprint 1 and I didn't get a notification for this comment.

**Comment by ccoffey1** [comment]
On it now!

**Comment by ccoffey1** [comment]
Also: Failed to mention in the commit but fixed unit testing and added a bit more to test for quotes as well.
