### ISSUE TITLE
Reader won't go back to first word after reaching end of Document and pressing play

### ISSUE THREAD

**Issue by Dachkar** [dsarlo/word-by-word#37]
Tried fixing by adding a CheckIfAtEnd() inside ReadSelectedDocumentWordsAsync, but that was unsucessful.

**Comment by dsarlo** [comment]
There is an empty character at the end of every single _wordsToRead list...

**Comment by dsarlo** [comment]
This is also not intended behavior. Closing this issue. The user is supposed to reset back to the beginning if they'd like.
