### ISSUE TITLE
Add new context menu option for importing documents

### ISSUE THREAD

**Issue by dsarlo** [dsarlo/word-by-word#42]

**Comment by ccoffey1** [comment]
@dsarlo Maybe rather than having "Upload images" and "Upload documents" separately, we should have one universal option to upload all acceptable file types. It would make sense that the user may want to upload images and, say, PDF's in one go.

**Comment by dsarlo** [comment]
@ccoffey1 Yeah I had a TODO tag for it as a comment. I called it "making this method smart" or something. I guess I'll just do it now and check it in.

**Comment by ccoffey1** [comment]
Oh yeah I saw that, thought you meant the method just determining whether or not it should use OCR

**Comment by ccoffey1** [comment]
Accidental close, ignore that lol
